In [1]:
import pandas as pd
import random
seed=random.randint(0,100)
print(seed)

30


In [2]:
df=pd.read_csv('../data/out/augmented_shuffled.csv')
df = df.dropna(subset=["predicted_label"])
df = df[df["predicted_label"].str.strip() != ""]
df['predicted_label'].value_counts()

predicted_label
Valid                 7681
Irrelevant             480
Advertisement          172
Rant_Without_Visit     135
Name: count, dtype: int64

In [3]:
# Separate the DataFrame into 'valid' and 'non-valid' rows.
df_valid = df[df['predicted_label'] == 'Valid']
df_other = df[df['predicted_label'] != 'Valid']

# Randomly sample 300 rows from the 'valid' DataFrame.
df_valid_sampled = df_valid.sample(n=300, random_state=seed)

# Concatenate the sampled 'valid' rows with the 'non-valid' rows.
df = pd.concat([df_valid_sampled, df_other])

# Print the value counts of the updated DataFrame.
print(df['predicted_label'].value_counts())

predicted_label
Irrelevant            480
Valid                 300
Advertisement         172
Rant_Without_Visit    135
Name: count, dtype: int64


In [4]:
tag_mapping_dict = {
    'Valid': 0,
    'Advertisement': 1,
    'Irrelevant': 2,
    'Rant_Without_Visit': 3,
}

df['label'] = df['predicted_label'].map(tag_mapping_dict)


# REPLACE this:
# df[df['label']==None]
# WITH:
missing = df['label'].isna()
print("Unmapped labels:", int(missing.sum()))
assert missing.sum() == 0, "Found unmapped labels in predicted_label"


Unmapped labels: 0


In [5]:
df.head(2)

business_name                                               text  \
6466      Mi Tierra  Service is terrible.  The food is nothing like...   
6812  Country Pride  Adrienne our waitress was wonderful!!  The foo...   

     predicted_label                                  prediction_reason  \
6466           Valid  The review provides detailed feedback about a ...   
6812           Valid  The review describes a genuine dining experien...   

     description                category  label  
6466         NaN  ['Mexican restaurant']      0  
6812         NaN          ['Restaurant']      0

In [6]:
PROMPT_PREFIX="""
You are a top-tier content moderation expert specializing in the evaluation of Google Maps location reviews. 
Your task is to parse a JSON object containing review data and accurately classify it according to the following policies and rules.
"""

def create_json_from_row(row):
    """
    Converts a DataFrame row into a JSON-formatted string.
    """
    json_object = {
        "business_name": row["business_name"],
        "business_description": row["description"],
        "business_category": row["category"],
        "review_text": row["text"],
        # "review_length": len(row["text"]),
    }
    return str(json_object)
    # return PROMPT_PREFIX+str(json_object)

df['text'] = df.apply(create_json_from_row, axis=1)
df['text']


6466    {'business_name': 'Mi Tierra', 'business_descr...
6812    {'business_name': 'Country Pride', 'business_d...
2468    {'business_name': 'Gators and Friends', 'busin...
1059    {'business_name': 'Days Inn by Wyndham Lafayet...
6868    {'business_name': 'Evangeline Maid Bakery Outl...
                              ...                        
8442    {'business_name': 'Shamrock', 'business_descri...
8446    {'business_name': 'Blue Lagoon Spa', 'business...
8448    {'business_name': 'Sunrise Bakery Cafe', 'busi...
8462    {'business_name': 'Key Village Shopping Center...
8471    {'business_name': 'Pizza Palace Express', 'bus...
Name: text, Length: 1087, dtype: object

In [7]:
df_filtered = df.loc[:, ['text', 'label']]

In [8]:
from datasets import Dataset, DatasetDict
from sklearn.model_selection import train_test_split

train_df, val_df = train_test_split(
    df_filtered[['text','label']],
    test_size=0.2,
    random_state=seed,
    stratify=df_filtered['label']
)

train_dataset = Dataset.from_pandas(train_df.reset_index(drop=True))
val_dataset   = Dataset.from_pandas(val_df.reset_index(drop=True))

my_dataset_dict = DatasetDict({
    'train': train_dataset,
    'validation': val_dataset
}).remove_columns([])  # nothing to drop now

print(my_dataset_dict)


/home/zhangguibin/anaconda3/envs/dra_ykm/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


DatasetDict({
    train: Dataset({
        features: ['text', 'label'],
        num_rows: 869
    })
    validation: Dataset({
        features: ['text', 'label'],
        num_rows: 218
    })
})


In [9]:
val_df['label'].value_counts()

label
2    96
0    60
1    35
3    27
Name: count, dtype: int64

In [10]:
# gpu usage
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "1,2,3,4,5,6,7"

In [11]:
import torch

if torch.cuda.is_available():
    print(f"GPU is available. Device count: {torch.cuda.device_count()}")
    print(f"Current device: {torch.cuda.current_device()}")
    print(f"Device name: {torch.cuda.get_device_name(torch.cuda.current_device())}")
    device = torch.device("cuda")
else:
    print("No GPU available, using CPU.")
    device = torch.device("cpu")

GPU is available. Device count: 7
Current device: 0
Device name: NVIDIA L40S


In [12]:
from transformers import AutoTokenizer, DataCollatorWithPadding

checkpoint = "nlptown/bert-base-multilingual-uncased-sentiment"
tokenizer = AutoTokenizer.from_pretrained(checkpoint)

INSTRUCTION = (
    "Task: classify review for THIS business. "
    "Labels: Valid, Advertisement, Irrelevant, Rant_Without_Visit. "
    "Priority: Ad > Irrelevant > No-visit rant > Valid."
)

def tokenize_function(example):
    texts = example["text"]
    # texts is a list when batched=True; replicate the instruction to match length
    instr = [INSTRUCTION] * len(texts)
    return tokenizer(instr, texts, truncation=True, max_length=256)


tokenized_datasets = my_dataset_dict.map(tokenize_function, batched=True)
data_collator = DataCollatorWithPadding(tokenizer=tokenizer)

# drop any raw columns that may exist (prompted_text OR text, and any index col)
cols_to_drop = [c for c in tokenized_datasets["train"].column_names 
                if c in ["prompted_text", "text", "__index_level_0__"]]
if cols_to_drop:
    tokenized_datasets = tokenized_datasets.remove_columns(cols_to_drop)



Map: 100%|██████████| 218/218 [00:00<00:00, 5733.09 examples/s]


In [13]:
from transformers import AutoModelForSequenceClassification, TrainingArguments, Trainer
from sklearn.metrics import accuracy_score, f1_score
import numpy as np

model = AutoModelForSequenceClassification.from_pretrained(checkpoint, num_labels=4,ignore_mismatched_sizes=True)

# 简单评估指标（最小改动）
def compute_metrics(eval_pred):
    logits, labels = eval_pred
    preds = np.argmax(logits, axis=-1)
    return {
        "accuracy": accuracy_score(labels, preds),
        "f1_weighted": f1_score(labels, preds, average="weighted", zero_division=0),
        "f1_macro": f1_score(labels, preds, average="macro", zero_division=0),
    }

# 2. 设置训练参数
training_args = TrainingArguments(
    output_dir=f"./results/{checkpoint}",
    num_train_epochs=6,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=64,
    warmup_ratio=0.1,
    weight_decay=0.01,
    logging_dir="./logs",
    # Add these two lines to show training loss
    logging_strategy="steps",
    logging_steps=6,  
    fp16=True,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="f1_macro",
    greater_is_better=True,
)

# 假设你已经准备好了 tokenized_datasets
# tokenized_datasets['train'], tokenized_datasets['test']

# 3. 初始化 Trainer
trainer = Trainer(
    model=model,                                   # 模型会被自动移动到GPU
    args=training_args,                            # 训练参数
    train_dataset=tokenized_datasets['train'],
    eval_dataset=tokenized_datasets["validation"],
    data_collator=data_collator,
    processing_class=tokenizer,                           # （替换 processing_class）
    compute_metrics=compute_metrics,               # 增加评估指标
)

# 4. 开始训练
#    在调用 .train() 时，每一批数据也会被自动发送到GPU
trainer.train()


Some weights of BertForSequenceClassification were not initialized from the model checkpoint at nlptown/bert-base-multilingual-uncased-sentiment and are newly initialized because the shapes did not match:
- classifier.bias: found shape torch.Size([5]) in the checkpoint and torch.Size([4]) in the model instantiated
- classifier.weight: found shape torch.Size([5, 768]) in the checkpoint and torch.Size([4, 768]) in the model instantiated
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/home/zhangguibin/anaconda3/envs/dra_ykm/lib/python3.11/site-packages/torch/nn/parallel/_functions.py:71: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn(


/home/zhangguibin/anaconda3/envs/dra_ykm/lib/python3.11/site-packages/torch/nn/parallel/_functions.py:71: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn(
/home/zhangguibin/anaconda3/envs/dra_ykm/lib/python3.11/site-packages/torch/nn/parallel/_functions.py:71: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn(
/home/zhangguibin/anaconda3/envs/dra_ykm/lib/python3.11/site-packages/torch/nn/parallel/_functions.py:71: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn(
/home/zhangguibin/anaconda3/envs/dra_ykm/lib/python3.11/site-packages/torch/nn/parallel/_functions.py:71: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vecto

TrainOutput(global_step=48, training_loss=0.6779810115695, metrics={'train_runtime': 66.1658, 'train_samples_per_second': 78.802, 'train_steps_per_second': 0.725, 'total_flos': 666661385450112.0, 'train_loss': 0.6779810115695, 'epoch': 6.0})

In [17]:
from sklearn.metrics import classification_report, confusion_matrix
import numpy as np

id2label = {0: "Valid", 1: "Advertisement", 2: "Irrelevant", 3: "Rant_Without_Visit"}
all_labels = [0, 1, 2, 3]
target_names = [id2label[i] for i in all_labels]

predictions = trainer.predict(tokenized_datasets["validation"])
logits = predictions.predictions
labels = predictions.label_ids
preds = np.argmax(logits, axis=-1).astype(int)


print(classification_report(
    labels, preds,
    labels=all_labels,              # <-- ensure fixed label set
    target_names=target_names,
    zero_division=0,
    digits=3
))

print("Confusion matrix:\n", confusion_matrix(labels, preds, labels=all_labels))

/home/zhangguibin/anaconda3/envs/dra_ykm/lib/python3.11/site-packages/torch/nn/parallel/_functions.py:71: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn(


                    precision    recall  f1-score   support

             Valid      0.806     0.833     0.820        60
     Advertisement      0.943     0.943     0.943        35
        Irrelevant      0.914     0.885     0.899        96
Rant_Without_Visit      0.929     0.963     0.945        27

          accuracy                          0.890       218
         macro avg      0.898     0.906     0.902       218
      weighted avg      0.891     0.890     0.890       218

Confusion matrix:
 [[50  1  7  2]
 [ 1 33  1  0]
 [11  0 85  0]
 [ 0  1  0 26]]


In [ ]:
# from scipy.special import softmax

# threshold=0.4
# probs = softmax(logits, axis=-1)

# # 默认预测
# preds_default = np.argmax(probs, axis=-1)

# # --- 核心改动在这里 ---
# # 假设 'Irrelevant' 是标签 2
# irrelevant_probs = probs[:, 2] 

# # 如果 'Irrelevant' 的概率超过了我们设定的低阈值，就强制预测为 'Irrelevant'
# # 否则，才使用默认的最高概率预测
# preds_adjusted = np.where(irrelevant_probs > threshold, 2, preds_default)

# preds=preds_adjusted

# print(classification_report(
#     labels, preds,
#     labels=all_labels,              # <-- ensure fixed label set
#     target_names=target_names,
#     zero_division=0,
#     digits=3
# ))

# print("Confusion matrix:\n", confusion_matrix(labels, preds, labels=all_labels))


In [18]:
import numpy as np
from datasets import Dataset

# 你已有的代码
predictions = trainer.predict(tokenized_datasets["validation"])
logits = predictions.predictions
labels = predictions.label_ids
preds = np.argmax(logits, axis=-1).astype(int)

# -------------------- 核心代码开始 --------------------

# 1. 创建一个布尔掩码 (boolean mask)，标记出所有被预测为 0 的位置
#    mask 会是一个 True/False 的数组，例如 [True, False, True, ...]
mask = (preds == 0)
print(f"第一阶段预测为 'label=0' 的数据有 {mask.sum()} 条。")

# 2. 从原始验证集中，根据掩码筛选出这些数据
#    我们使用 .select() 方法，它需要的是索引号，而不是True/False
indices_to_stage2 = np.where(mask)[0]

# 创建一个新的数据集，专门用于第二阶段的预测
stage2_dataset = tokenized_datasets["validation"].select(indices_to_stage2)

print("已成功创建用于第二阶段预测的新数据集：")
print(stage2_dataset)

# 为了后续合并结果，我们还需要筛选出这些数据的真实标签
stage2_labels = labels[mask]

# 假设 stage2_dataset 已经创建好了
# stage2_dataset = tokenized_datasets["validation"].select(indices_to_stage2)

# --- 把数据集保存到硬盘 ---

# 1. 定义一个你想要保存的文件夹名称
save_path = "./stage2_filtered_data"

# 2. 调用 .save_to_disk() 方法
print(f"正在将数据集保存到 '{save_path}' ...")
stage2_dataset.save_to_disk(save_path)
print("保存成功！")

/home/zhangguibin/anaconda3/envs/dra_ykm/lib/python3.11/site-packages/torch/nn/parallel/_functions.py:71: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn(


第一阶段预测为 'label=0' 的数据有 62 条。
已成功创建用于第二阶段预测的新数据集：
Dataset({
    features: ['label', 'input_ids', 'token_type_ids', 'attention_mask'],
    num_rows: 62
})
正在将数据集保存到 './stage2_filtered_data' ...


Saving the dataset (1/1 shards): 100%|██████████| 62/62 [00:00<00:00, 15490.04 examples/s]

保存成功！


In [ ]:
from datasets import load_from_disk

# --- 从硬盘加载之前保存的数据集 ---

# 1. 指定之前保存的那个文件夹路径
load_path = "./stage2_filtered_data"

# 2. 调用 load_from_disk() 函数
print(f"正在从 '{load_path}' 加载数据集...")
loaded_stage2_dataset = load_from_disk(load_path)
print("加载成功！")

# 验证一下加载回来的数据集
print("\n加载后的数据集信息：")
print(loaded_stage2_dataset)

# 你可以看到，它的结构和内容与保存前完全一样
# 现在你可以直接用它进行第二阶段的训练或预测了
#
# 例如:


正在从 './stage2_filtered_data' 加载数据集...
加载成功！

加载后的数据集信息：
Dataset({
    features: ['label', 'input_ids', 'token_type_ids', 'attention_mask'],
    num_rows: 62
})


In [ ]:
from sklearn.metrics import classification_report, confusion_matrix
import numpy as np

id2label = {0: "Valid", 1: "Advertisement", 2: "Irrelevant", 3: "Rant_Without_Visit"}
all_labels = [0, 1, 2, 3]
target_names = [id2label[i] for i in all_labels]
# stage2_predictions = trainer_stage2.predict(loaded_stage2_dataset)
predictions = trainer.predict(loaded_stage2_dataset)
logits = predictions.predictions
labels = predictions.label_ids
preds = np.argmax(logits, axis=-1).astype(int)


print(classification_report(
    labels, preds,
    labels=all_labels,              # <-- ensure fixed label set
    target_names=target_names,
    zero_division=0,
    digits=3
))

print("Confusion matrix:\n", confusion_matrix(labels, preds, labels=all_labels))

/home/zhangguibin/anaconda3/envs/dra_ykm/lib/python3.11/site-packages/torch/nn/parallel/_functions.py:71: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn(


                    precision    recall  f1-score   support

             Valid      0.806     0.833     0.820        60
     Advertisement      0.943     0.943     0.943        35
        Irrelevant      0.914     0.885     0.899        96
Rant_Without_Visit      0.929     0.963     0.945        27

          accuracy                          0.890       218
         macro avg      0.898     0.906     0.902       218
      weighted avg      0.891     0.890     0.890       218

Confusion matrix:
 [[50  1  7  2]
 [ 1 33  1  0]
 [11  0 85  0]
 [ 0  1  0 26]]
